SELECT 
(SELECT SUM(IF(IFNULL(CURRENCY_CODE, 'KRW')='KRW',EVAL_AMT,EVAL_AMT*(SELECT RATE FROM betterday_db.BD_EXCHANGE_RATE B
   																WHERE B.CURRENCY_CODE = miap.CURRENCY_CODE
                                								AND date_format(CRT_DT,"%Y-%m-%d") = miap.BASE_DATE limit 1))) AS AMT_SUM 
FROM MD_INVEST_ACCOUNTS_PRODUCTS miap 
WHERE miap.INVEST_ACCOUNTS_ID IN (SELECT ID FROM MD_INVEST_ACCOUNTS mia
									WHERE mia.TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN mut
															WHERE mut.BDAY_CUST_ID = 268)))
/
(SELECT (SELECT SUM(IF(IFNULL(CURRENCY_CODE, 'KRW')='KRW',EVAL_AMT,EVAL_AMT*(SELECT RATE FROM betterday_db.BD_EXCHANGE_RATE B
   																WHERE B.CURRENCY_CODE = miap.CURRENCY_CODE
                                								AND date_format(CRT_DT,"%Y-%m-%d") = miap.BASE_DATE limit 1))) AS AMT_SUM 
FROM MD_INVEST_ACCOUNTS_PRODUCTS miap
WHERE miap.INVEST_ACCOUNTS_ID IN (SELECT ID FROM MD_INVEST_ACCOUNTS mia
									WHERE mia.TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN mut
															WHERE mut.BDAY_CUST_ID = 268)))
+
(SELECT SUM(IF(mbadd.BALANCE_AMT<0,0,mbadd.BALANCE_AMT)) FROM MD_BANK_ACCOUNTS_DEPOSIT_DETAIL mbadd
WHERE mbadd.BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS mba 
								WHERE mba.TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN mut
														WHERE mut.BDAY_CUST_ID = 268)
								AND mba.IS_CONSENT=1
								AND mba.ACCOUNT_TYPE IN (1001,1002,1003,1999,2001,2002,2003,2004,2999)
								AND mba.ACCOUNT_STATUS =1 )))
								
# invest_amt
SELECT SUM(IF(IFNULL(CURRENCY_CODE, 'KRW')='KRW',EVAL_AMT,EVAL_AMT*(SELECT RATE FROM betterday_db.BD_EXCHANGE_RATE B
   																WHERE B.CURRENCY_CODE = miap.CURRENCY_CODE
                                								AND date_format(CRT_DT,"%Y-%m-%d") = miap.BASE_DATE limit 1))) AS AMT_SUM 
FROM MD_INVEST_ACCOUNTS_PRODUCTS miap 
WHERE miap.INVEST_ACCOUNTS_ID IN (SELECT ID FROM MD_INVEST_ACCOUNTS mia
									WHERE mia.TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN mut
															WHERE mut.BDAY_CUST_ID = 268))
															
# eval_amt										
SELECT SUM(IF(mbadd.BALANCE_AMT<0,0,mbadd.BALANCE_AMT)) FROM MD_BANK_ACCOUNTS_DEPOSIT_DETAIL mbadd
WHERE mbadd.BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS mba 
								WHERE mba.TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN mut
														WHERE mut.BDAY_CUST_ID = 268)
								AND mba.IS_CONSENT=1
								AND mba.ACCOUNT_TYPE IN (1001,1002,1003,1999,2001,2002,2003,2004,2999)
								AND mba.ACCOUNT_STATUS =1 )

CALL get_invest_rate(268);




# 전체고객
SELECT ID FROM BDAY_CUST

# CLUSTER1 NOT- 존재 계좌
SELECT mut.BDAY_CUST_ID  FROM MD_BANK_IRPS mbi, MD_INSU_IRPS mii , MD_INVEST_IRPS mii2, MD_USER_TOKEN mut  
WHERE (mbi.TOKEN_ID = mut.ID OR mii.TOKEN_ID = mut.ID OR mii2.TOKEN_ID = mut.ID)
GROUP BY mut.BDAY_CUST_ID;

# CLUSTER2 - 연금납입금액 부족자 (납입금액 400만원 이하)
SELECT mut.BDAY_CUST_ID, SUM(miap.PAID_IN_AMT) FROM MD_INVEST_ACCOUNTS_PENSION miap , MD_INVEST_ACCOUNTS mia , MD_USER_TOKEN mut 
WHERE miap.INVEST_ACCOUNTS_ID =  mia.ID 
AND mia.TOKEN_ID = mut.ID 
AND mia.IS_CONSENT=1
GROUP BY mut.BDAY_CUST_ID
HAVING SUM(miap.PAID_IN_AMT) <= 4000000;


# CLUSTER3 - 연금저축보험
SELECT mut.BDAY_CUST_ID FROM MD_INSU_INSURANCES mii , MD_USER_TOKEN mut 
WHERE mii.INSU_TYPE = 09
AND mii.INSU_STATUS = 02
AND mii.IS_CONSENT =1
AND mii.TOKEN_ID = mut.ID
GROUP BY mut.BDAY_CUST_ID;

# CLUSTER4 - 개인연금펀드 손실 발생자 
SELECT mut.BDAY_CUST_ID , COUNT(*) FROM MD_INVEST_ACCOUNTS_PRODUCTS miap , MD_INVEST_ACCOUNTS mia , MD_USER_TOKEN mut 
WHERE miap.INVEST_ACCOUNTS_ID =  mia.ID dd

AND mia.IS_CONSENT=1
AND miap.PROD_TYPE IN (413, 414, 415)
AND miap.PURCHASE_AMT > miap.EVAL_AMT
GROUP BY mut.BDAY_CUST_ID;

######################################################################################
# 금투연금
SELECT mut.BDAY_CUST_ID FROM MD_INVEST_ACCOUNTS mia, MD_USER_TOKEN mut
WHERE mia.TOKEN_ID = mut.ID
AND mia.ACCOUNT_TYPE = 105
GROUP BY mut.BDAY_CUST_ID;

SELECT * FROM MD_INVEST_ACCOUNTS mia WHERE mia.TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN mut
															WHERE mut.BDAY_CUST_ID=268)
AND mia.ACCOUNT_TYPE = 105

#은행연금 및 펀드
SELECT * FROM MD_BANK_ACCOUNTS mba , MD_USER_TOKEN mut 
WHERE ACCOUNT_TYPE IN (2001,2002,2003,2004,2999)
AND (PROD_NAME LIKE '%펀드%')
AND mba.TOKEN_ID = mut.ID
GROUP BY mut.BDAY_CUST_ID; 

SELECT * FROM MD_BANK_ACCOUNTS mba WHERE mba.TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN mut
															WHERE mut.BDAY_CUST_ID = 10)
AND mba.ACCOUNT_TYPE IN (2001,2002,2003,2004,2999)
AND (mba.PROD_NAME LIKE '%연금%' OR mba.PROD_NAME LIKE '%펀드%')


# 내 아이디 - 2107











