SELECT SUM((DATEDIFF(VAR_TO_DATE, TRANS_DTIME)+1)/(DATEDIFF(VAR_TO_DATE, VAR_FROM_DATE)+1)*if(TRANS_TYPE=301,SETTLE_AMT,-SETTLE_AMT)*IF(A.CURRENCY_CODE='KRW' OR A.CURRENCY_CODE is NULL,1,(SELECT RATE FROM betterday_db.BD_EXCHANGE_RATE B
					WHERE B.CURRENCY_CODE = A.CURRENCY_CODE
					AND date_format(CRT_DT,"%Y-%m-%d") = date_format(A.TRANS_DTIME,"%Y-%m-%d") 
					limit 1))) INTO INOUT_0
FROM MD_INVEST_ACCOUNTS_TRANS_HIST A
JOIN (
	SELECT FROM_ACC.INVEST_ACCOUNTS_ID
	FROM (
		SELECT DISTINCT C.INVEST_ACCOUNTS_ID
		FROM(
			SELECT A1.INVEST_ACCOUNTS_ID, DATE_SUB(A1.BASE_DATE, INTERVAL B.offset DAY) AS JJINT
			FROM
			MD_INVEST_ACCOUNTS_PRODUCTS_HIST A1
			INNER JOIN 
			(SELECT Z.ID, Z.TOKEN_ID, Z.IS_CONSENT, Z.ACCOUNT_TYPE, X.offset FROM (SELECT * FROM MD_INVEST_ACCOUNTS WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN mut WHERE BDAY_CUST_ID=VAR_BDAY_CUST_ID)) Z 
			LEFT OUTER JOIN (SELECT ID, ORG_CODE FROM MD_USER_TOKEN WHERE BDAY_CUST_ID=VAR_BDAY_CUST_ID) Y ON Z.TOKEN_ID = Y.ID
			LEFT OUTER JOIN (SELECT * FROM betterday_admin.bo_stock_org_offset_bs_mngs WHERE bs_typ = 'PRODUCTS') X ON Y.ORG_CODE = X.org_cd COLLATE utf8mb4_unicode_ci) B
			ON A1.INVEST_ACCOUNTS_ID = B.ID
		) C
		WHERE C.JJINT = VAR_FROM_DATE
	) FROM_ACC
	JOIN (
		SELECT DISTINCT C.INVEST_ACCOUNTS_ID
		FROM(
			SELECT A1.INVEST_ACCOUNTS_ID, DATE_SUB(A1.BASE_DATE, INTERVAL B.offset DAY) AS JJINT
			FROM
			MD_INVEST_ACCOUNTS_PRODUCTS_HIST A1
			INNER JOIN 
			(SELECT Z.ID, Z.TOKEN_ID, Z.IS_CONSENT, Z.ACCOUNT_TYPE, X.offset FROM (SELECT * FROM MD_INVEST_ACCOUNTS WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN mut WHERE BDAY_CUST_ID=VAR_BDAY_CUST_ID)) Z 
			LEFT OUTER JOIN (SELECT ID, ORG_CODE FROM MD_USER_TOKEN WHERE BDAY_CUST_ID=VAR_BDAY_CUST_ID) Y ON Z.TOKEN_ID = Y.ID
			LEFT OUTER JOIN (SELECT * FROM betterday_admin.bo_stock_org_offset_bs_mngs WHERE bs_typ = 'PRODUCTS') X ON Y.ORG_CODE = X.org_cd COLLATE utf8mb4_unicode_ci) B
			ON A1.INVEST_ACCOUNTS_ID = B.ID
		) C
		WHERE C.JJINT = VAR_TO_DATE
	) TO_ACC
	ON FROM_ACC.INVEST_ACCOUNTS_ID = TO_ACC.INVEST_ACCOUNTS_ID
) ACC_ID
ON ACC_ID.INVEST_ACCOUNTS_ID = A.INVEST_ACCOUNTS_ID
WHERE A.INVEST_ACCOUNTS_ID IN(SELECT ID FROM MD_INVEST_ACCOUNTS mia WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN mut WHERE BDAY_CUST_ID=VAR_BDAY_CUST_ID))
AND TRANS_DTIME BETWEEN CAST(VAR_FROM_DATE AS DATETIME) AND CAST(DATE_ADD(VAR_TO_DATE, INTERVAL 1 DAY) AS DATETIME)
AND (TRANS_TYPE = 301 OR TRANS_TYPE = 302)
AND TRANS_TYPE_DETAIL Not like '공모%'
AND TRANS_TYPE_DETAIL Not like '배당%'
AND TRANS_TYPE_DETAIL Not like '%환전%';

SELECT SUM((DATEDIFF(VAR_TO_DATE, TRANS_DTIME)+1)/(DATEDIFF(VAR_TO_DATE, VAR_FROM_DATE)+1)*IF(A.CURRENCY_CODE='KRW' OR A.CURRENCY_CODE is NULL, IF(TRANS_TYPE=321 OR TRANS_TYPE=381,TRANS_NUM * BASE_AMT,-TRANS_NUM * BASE_AMT),IF(TRANS_TYPE=321 OR TRANS_TYPE=381,TRANS_NUM * BASE_AMT,-TRANS_NUM * BASE_AMT)*(SELECT RATE FROM betterday_db.BD_EXCHANGE_RATE B
			 		WHERE B.CURRENCY_CODE = A.CURRENCY_CODE
					AND date_format(CRT_DT,"%Y-%m-%d") = date_format(A.TRANS_DTIME,"%Y-%m-%d") 
					limit 1))) INTO INOUT_1
FROM MD_INVEST_ACCOUNTS_TRANS_HIST A
JOIN (
	SELECT FROM_ACC.INVEST_ACCOUNTS_ID
	FROM (
		SELECT DISTINCT C.INVEST_ACCOUNTS_ID
		FROM(
			SELECT A1.INVEST_ACCOUNTS_ID, DATE_SUB(A1.BASE_DATE, INTERVAL B.offset DAY) AS JJINT
			FROM
			MD_INVEST_ACCOUNTS_PRODUCTS_HIST A1
			INNER JOIN 
			(SELECT Z.ID, Z.TOKEN_ID, Z.IS_CONSENT, Z.ACCOUNT_TYPE, X.offset FROM (SELECT * FROM MD_INVEST_ACCOUNTS WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN mut WHERE BDAY_CUST_ID=VAR_BDAY_CUST_ID)) Z 
			LEFT OUTER JOIN (SELECT ID, ORG_CODE FROM MD_USER_TOKEN WHERE BDAY_CUST_ID=VAR_BDAY_CUST_ID) Y ON Z.TOKEN_ID = Y.ID
			LEFT OUTER JOIN (SELECT * FROM betterday_admin.bo_stock_org_offset_bs_mngs WHERE bs_typ = 'PRODUCTS') X ON Y.ORG_CODE = X.org_cd COLLATE utf8mb4_unicode_ci) B
			ON A1.INVEST_ACCOUNTS_ID = B.ID
		) C
		WHERE C.JJINT = VAR_FROM_DATE
	) FROM_ACC
	JOIN (
		SELECT DISTINCT C.INVEST_ACCOUNTS_ID
		FROM(
			SELECT A1.INVEST_ACCOUNTS_ID, DATE_SUB(A1.BASE_DATE, INTERVAL B.offset DAY) AS JJINT
			FROM
			MD_INVEST_ACCOUNTS_PRODUCTS_HIST A1
			INNER JOIN 
			(SELECT Z.ID, Z.TOKEN_ID, Z.IS_CONSENT, Z.ACCOUNT_TYPE, X.offset FROM (SELECT * FROM MD_INVEST_ACCOUNTS WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN mut WHERE BDAY_CUST_ID=VAR_BDAY_CUST_ID)) Z 
			LEFT OUTER JOIN (SELECT ID, ORG_CODE FROM MD_USER_TOKEN WHERE BDAY_CUST_ID=VAR_BDAY_CUST_ID) Y ON Z.TOKEN_ID = Y.ID
			LEFT OUTER JOIN (SELECT * FROM betterday_admin.bo_stock_org_offset_bs_mngs WHERE bs_typ = 'PRODUCTS') X ON Y.ORG_CODE = X.org_cd COLLATE utf8mb4_unicode_ci) B
			ON A1.INVEST_ACCOUNTS_ID = B.ID
		) C
		WHERE C.JJINT = VAR_TO_DATE
	) TO_ACC
	ON FROM_ACC.INVEST_ACCOUNTS_ID = TO_ACC.INVEST_ACCOUNTS_ID
) ACC_ID
ON ACC_ID.INVEST_ACCOUNTS_ID = A.INVEST_ACCOUNTS_ID
WHERE A.INVEST_ACCOUNTS_ID IN(SELECT ID FROM MD_INVEST_ACCOUNTS mia WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN mut WHERE BDAY_CUST_ID=VAR_BDAY_CUST_ID))
AND TRANS_DTIME BETWEEN CAST(VAR_FROM_DATE AS DATETIME) AND CAST(DATE_ADD(VAR_TO_DATE, INTERVAL 1 DAY) AS DATETIME)
AND (TRANS_TYPE = 321 OR TRANS_TYPE = 322 OR TRANS_TYPE = 381)
AND TRANS_TYPE_DETAIL Not like '공모%'
AND TRANS_TYPE_DETAIL Not like '배당%';

SELECT IFNULL(InOut_0, 0) INTO INOUT_0;
SELECT IFNULL(InOut_1, 0) INTO INOUT_1;
   
SET INOUT_TOTAL = INOUT_0 + INOUT_1;
