SELECT SUM(PRINCIPAL_AMT) FROM MD_BANK_ACCOUNTS_LOAN_TRANSACTIONS
WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS 
                                                        WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN
                                                                                                WHERE BDAY_CUST_ID = 268)
                                                        AND IS_CONSENT=1
                                                        AND TRANS_TYPE=2
                                                        AND TRANS_DTIME BETWEEN DATE_SUB(NOW(), INTERVAL 6 MONTH) AND NOW());
                                                        
                                                       
SELECT * FROM MD_BANK_ACCOUNTS_LOAN_TRANSACTIONS
WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = 39)
AND IS_CONSENT=1)
AND TRANS_TYPE=2
AND TRANS_DTIME
	BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 39), INTERVAL 6 MONTH))
	AND (SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 39);


SELECT 
(SELECT COUNT(*) FROM betterday_db.MD_BANK_ACCOUNTS_DEPOSIT_TRANSACTIONS WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM betterday_db.MD_BANK_ACCOUNTS
  WHERE TOKEN_ID IN (SELECT ID FROM betterday_db.MD_USER_TOKEN
  WHERE BDAY_CUST_ID = 268)
 AND IS_CONSENT=1 AND ACCOUNT_TYPE = 1001 AND ACCOUNT_STATUS=1)
 AND TRANS_TYPE =2
 AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 518), INTERVAL 3 MONTH)) AND
                                                 (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 518), INTERVAL 2 MONTH)))
-
(SELECT COUNT(*)-- A.BANK_ACCOUNTS_ID,B.BANK_ACCOUNTS_ID, A.TRANS_DTIME, B.TRANS_DTIME,A.TRANS_AMT,B.TRANS_AMT,A.TRANS_TYPE,B.TRANS_TYPE
 FROM
 (SELECT * FROM MD_BANK_ACCOUNTS_DEPOSIT_TRANSACTIONS 
        WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = 268)
        AND IS_CONSENT =1 AND ACCOUNT_TYPE = 1001 AND ACCOUNT_STATUS=1)
        AND TRANS_TYPE =2
        AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 518), INTERVAL 3 MONTH)) AND
                                                        (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 518), INTERVAL 2 MONTH))) A, -- 출금
 (SELECT * FROM MD_BANK_ACCOUNTS_DEPOSIT_TRANSACTIONS 
        WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = 268)
        AND IS_CONSENT =1 AND ACCOUNT_TYPE = 1001 AND ACCOUNT_STATUS=1)
        AND TRANS_TYPE =3
        AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 518), INTERVAL 3 MONTH)) AND
                                                        (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 518), INTERVAL 2 MONTH))) B -- 입금
 WHERE A.TRANS_AMT = B.TRANS_AMT
 AND DATE_FORMAT(A.TRANS_DTIME,"%Y-%m-%d") = DATE_FORMAT(B.TRANS_DTIME,"%Y-%m-%d")) AS '총 출금횟수';
 
############################################################                                 
SELECT A.ID, MAX(B.CRT_DT) AS "Last Login Time"
, CSS_CARD_56(A.ID)
FROM betterday_db.BDAY_CUST A, betterday_db.BDAY_CUST_LOGIN_HIST B
WHERE A.ID = B.CUST_ID
GROUP BY B.CUST_ID
ORDER BY A.ID ASC;
##############################################################       
       
SELECT IF((SELECT COUNT(*) FROM  MD_BANK_ACCOUNTS_DEPOSIT_TRANSACTIONS WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS
        WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = VAR_BDAY_CUST_ID)
        AND IS_CONSENT = 1))=0,NULL,COUNT(*))
        
FROM MD_BANK_ACCOUNTS_DEPOSIT_TRANSACTIONS mbadt
LEFT OUTER JOIN MD_BANK_ACCOUNTS mba 
ON mbadt.BANK_ACCOUNTS_ID = mba.ID
WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS
        WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = 461)
        AND IS_CONSENT = 1)
AND mba.ACCOUNT_TYPE = 1001
AND mba.ACCOUNT_STATUS = 1
AND BALANCE_AMT = 0
AND TRANS_TYPE = 2
AND ((TRANS_MEMO LIKE '%캐피탈%') OR (TRANS_MEMO LIKE '%저축은행%') OR (TRANS_MEMO LIKE '%커머셜%'))
AND mbadt.TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 461), INTERVAL 1 MONTH)) AND
                                                (SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 461);

##############################################################
  
SELECT COUNT(IF(STATUS = '01',APPROVED_AMT,-APPROVED_AMT)) INTO CARD_55 FROM betterday_db.MD_CARD_APPROVAL_DOMESTIC WHERE CARD_CARDS_ID IN (SELECT ID FROM betterday_db.MD_CARD_CARDS
WHERE TOKEN_ID IN (SELECT ID FROM betterday_db.MD_USER_TOKEN
WHERE BDAY_CUST_ID = VAR_BDAY_CUST_ID))
AND APPROVED_DTIME
        BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = VAR_BDAY_CUST_ID), INTERVAL 1 MONTH))
        AND (SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = VAR_BDAY_CUST_ID)
AND (HOUR(APPROVED_DTIME) BETWEEN 1 AND 6 OR HOUR(APPROVED_DTIME) BETWEEN 21 AND 24)
AND (STATUS = '01' OR STATUS = '02');

##############################################################  
SELECT 
(SELECT IF((SELECT COUNT(*) FROM  MD_BANK_ACCOUNTS_DEPOSIT_TRANSACTIONS WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS
        WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = 461)
        AND IS_CONSENT = 1))=0,NULL,COUNT(*)) FROM betterday_db.MD_BANK_ACCOUNTS_DEPOSIT_TRANSACTIONS WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM betterday_db.MD_BANK_ACCOUNTS
  WHERE TOKEN_ID IN (SELECT ID FROM betterday_db.MD_USER_TOKEN
  WHERE BDAY_CUST_ID = 461)
 AND IS_CONSENT=1 AND ACCOUNT_TYPE = 1001 AND ACCOUNT_STATUS=1)
 AND TRANS_TYPE =2
 AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 461), INTERVAL 2 MONTH)) AND
                                                 (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 461), INTERVAL 1 MONTH)))
-
(SELECT IF((SELECT COUNT(*) FROM  MD_BANK_ACCOUNTS_DEPOSIT_TRANSACTIONS WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS
        WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = 461)
        AND IS_CONSENT = 1))=0,NULL,COUNT(*))-- A.BANK_ACCOUNTS_ID,B.BANK_ACCOUNTS_ID, A.TRANS_DTIME, B.TRANS_DTIME,A.TRANS_AMT,B.TRANS_AMT,A.TRANS_TYPE,B.TRANS_TYPE
 FROM
 (SELECT * FROM MD_BANK_ACCOUNTS_DEPOSIT_TRANSACTIONS 
        WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = 461)
        AND IS_CONSENT =1 AND ACCOUNT_TYPE = 1001 AND ACCOUNT_STATUS=1)
        AND TRANS_TYPE =2
        AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 461), INTERVAL 2 MONTH)) AND
                                                        (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 461), INTERVAL 1 MONTH))) A, -- 출금
 (SELECT * FROM MD_BANK_ACCOUNTS_DEPOSIT_TRANSACTIONS 
        WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = 461)
        AND IS_CONSENT =1 AND ACCOUNT_TYPE = 1001 AND ACCOUNT_STATUS=1)
        AND TRANS_TYPE =3
        AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 461), INTERVAL 2 MONTH)) AND
                                                        (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 461), INTERVAL 1 MONTH))) B -- 입금
 WHERE A.TRANS_AMT = B.TRANS_AMT
 AND DATE_FORMAT(A.TRANS_DTIME,"%Y-%m-%d") = DATE_FORMAT(B.TRANS_DTIME,"%Y-%m-%d")) AS '총 출금횟수';
 
##############################################################
SELECT IF((SELECT COUNT(*) FROM  MD_BANK_ACCOUNTS_DEPOSIT_TRANSACTIONS WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS
        WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = 1160)
        AND IS_CONSENT = 1))=0,NULL,COUNT(mbadt.ID))
FROM MD_BANK_ACCOUNTS_DEPOSIT_TRANSACTIONS mbadt
LEFT OUTER JOIN MD_BANK_ACCOUNTS mba 
ON mbadt.BANK_ACCOUNTS_ID = mba.ID
WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS
        WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = 1160)
        AND IS_CONSENT = 1)
AND mba.ACCOUNT_TYPE = 1001
AND mba.ACCOUNT_STATUS = 1
AND mbadt.BALANCE_AMT = 0
AND mbadt.TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 1160), INTERVAL 1 MONTH)) AND
                                                          (SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 1160);
                                                          
##############################################################
SELECT IF((SELECT COUNT(*) FROM  MD_CARD_APPROVAL_DOMESTIC WHERE CARD_CARDS_ID IN (SELECT ID FROM MD_CARD_CARDS
        WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = 268)
        AND IS_CONSENT = 1))=0,NULL,COUNT(IF(STATUS = '01', STATUS, null))-COUNT(IF(STATUS = '02', STATUS, null)))
FROM betterday_db.MD_CARD_APPROVAL_DOMESTIC
WHERE CARD_CARDS_ID IN (SELECT ID FROM betterday_db.MD_CARD_CARDS WHERE TOKEN_ID IN (SELECT ID FROM betterday_db.MD_USER_TOKEN WHERE BDAY_CUST_ID = 268)
																	AND IS_CONSENT =1)
AND APPROVED_DTIME
        BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 268), INTERVAL 1 MONTH))
        AND (SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 268)
AND (STATUS = '01' OR STATUS = '02');

#################################################################
SELECT IF((SELECT COUNT(*) FROM  MD_CARD_APPROVAL_DOMESTIC WHERE CARD_CARDS_ID IN (SELECT ID FROM MD_CARD_CARDS
        WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = 268)
        AND IS_CONSENT = 1))=0,NULL,COUNT(IF(STATUS = '01',APPROVED_AMT,-APPROVED_AMT)))
FROM betterday_db.MD_CARD_APPROVAL_DOMESTIC WHERE CARD_CARDS_ID IN (SELECT ID FROM betterday_db.MD_CARD_CARDS
WHERE TOKEN_ID IN (SELECT ID FROM betterday_db.MD_USER_TOKEN
WHERE BDAY_CUST_ID = 268))
AND APPROVED_DTIME
        BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 268), INTERVAL 1 MONTH))
        AND (SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 268)
AND DAYOFWEEK(APPROVED_DTIME) BETWEEN 2 AND 6
AND HOUR(APPROVED_DTIME) BETWEEN 6 AND 17
AND (STATUS = '01' OR STATUS = '02');


SELECT IF((SELECT COUNT(*) FROM  MD_CARD_APPROVAL_DOMESTIC WHERE CARD_CARDS_ID IN (SELECT ID FROM MD_CARD_CARDS
        WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = 268)
        AND IS_CONSENT = 1))=0,NULL,COUNT(IF(STATUS = '01',APPROVED_AMT,-APPROVED_AMT))) INTO CARD_43 
FROM betterday_db.MD_CARD_APPROVAL_DOMESTIC WHERE CARD_CARDS_ID IN (SELECT ID FROM betterday_db.MD_CARD_CARDS
WHERE TOKEN_ID IN (SELECT ID FROM betterday_db.MD_USER_TOKEN
WHERE BDAY_CUST_ID = VAR_BDAY_CUST_ID))
AND APPROVED_DTIME
        BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = VAR_BDAY_CUST_ID), INTERVAL 1 MONTH))
        AND (SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = VAR_BDAY_CUST_ID)
AND DAYOFWEEK(APPROVED_DTIME) BETWEEN 2 AND 6
AND HOUR(APPROVED_DTIME) BETWEEN 6 AND 17
AND (STATUS = '01' OR STATUS = '02');




IF((SELECT COUNT(*) FROM MD_INVEST_ACCOUNTS_PRODUCTS
WHERE INVEST_ACCOUNTS_ID IN (SELECT ID FROM MD_INVEST_ACCOUNTS
							WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN
												WHERE BDAY_CUST_ID = 268)
							AND IS_CONSENT =1))=0,NULL,COUNT(*))
				
			
SELECT IF((SELECT COUNT(*) FROM MD_INVEST_ACCOUNTS_TRANSACTIONS
WHERE INVEST_ACCOUNTS_ID IN (SELECT ID FROM MD_INVEST_ACCOUNTS
							WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN
												WHERE BDAY_CUST_ID = 268)
							AND IS_CONSENT =1))=0,NULL,COUNT(*)) FROM MD_INVEST_ACCOUNTS_TRANSACTIONS
WHERE INVEST_ACCOUNTS_ID IN (SELECT ID FROM MD_INVEST_ACCOUNTS
                                                          WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN
                                                                                                   WHERE BDAY_CUST_ID = 268)
                                                          AND IS_CONSENT=1)
AND PROD_CODE >='403' AND PROD_CODE<='421'
AND TRANS_TYPE ='301'
AND TRANS_DTIME
        BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 518), INTERVAL 1 MONTH))
        AND (SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 518)
        
        
        
        
SELECT CSS_INV_21(1051);		


#################################################################################################
# PROCEDURE
SELECT A.ID, MAX(B.CRT_DT) AS "Last Login Time"
, CSS_BANK_20_1(A.ID)
FROM betterday_db.BDAY_CUST A, betterday_db.BDAY_CUST_LOGIN_HIST B
WHERE A.ID = B.CUST_ID
GROUP BY B.CUST_ID
ORDER BY A.ID ASC;
#################################################################################################
SELECT 
(SELECT IF((SELECT COUNT(*) FROM  MD_BANK_ACCOUNTS_DEPOSIT_TRANS_HIST WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS
        WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = 268)
        AND IS_CONSENT = 1))=0,NULL,COUNT(*)) FROM betterday_db.MD_BANK_ACCOUNTS_DEPOSIT_TRANS_HIST WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM betterday_db.MD_BANK_ACCOUNTS
  WHERE TOKEN_ID IN (SELECT ID FROM betterday_db.MD_USER_TOKEN
  WHERE BDAY_CUST_ID = 268)
 AND IS_CONSENT=1 AND ACCOUNT_TYPE = 1001 AND ACCOUNT_STATUS=1)
 AND TRANS_TYPE =2
 AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 268), INTERVAL 3 MONTH)) AND
                                                 (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 268), INTERVAL 2 MONTH)))
-
(SELECT IF((SELECT COUNT(*) FROM  MD_BANK_ACCOUNTS_DEPOSIT_TRANS_HIST WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS
        WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = 268)
        AND IS_CONSENT = 1))=0,NULL,COUNT(DISTINCT A.ID))-- A.BANK_ACCOUNTS_ID,B.BANK_ACCOUNTS_ID, A.TRANS_DTIME, B.TRANS_DTIME,A.TRANS_AMT,B.TRANS_AMT,A.TRANS_TYPE,B.TRANS_TYPE
 FROM
 (SELECT * FROM MD_BANK_ACCOUNTS_DEPOSIT_TRANS_HIST 
        WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = 268)
        AND IS_CONSENT =1 AND ACCOUNT_TYPE = 1001 AND ACCOUNT_STATUS=1)
        AND TRANS_TYPE =2
        AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 268), INTERVAL 3 MONTH)) AND
                                                        (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 268), INTERVAL 2 MONTH))) A, -- 출금
 (SELECT * FROM MD_BANK_ACCOUNTS_DEPOSIT_TRANS_HIST 
        WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = 268)
        AND IS_CONSENT =1 AND ACCOUNT_TYPE = 1001 AND ACCOUNT_STATUS=1)
        AND TRANS_TYPE =3
        AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 268), INTERVAL 3 MONTH)) AND
                                                        (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 268), INTERVAL 2 MONTH))) B -- 입금
 WHERE A.TRANS_AMT = B.TRANS_AMT
 AND NOT (A.BANK_ACCOUNTS_ID = B.BANK_ACCOUNTS_ID)
 AND DATE_FORMAT(A.TRANS_DTIME,"%Y-%m-%d") = DATE_FORMAT(B.TRANS_DTIME,"%Y-%m-%d")) AS '총 출금횟수';


SELECT COUNT(*) AS '고객기준 예적금계좌 건수' FROM MD_BANK_ACCOUNTS
 WHERE  TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN
                      WHERE BDAY_CUST_ID = 268)
 AND IS_CONSENT=1 AND ACCOUNT_STATUS =1;
 
SELECT mut.BDAY_CUST_ID, COUNT(*) FROM MD_BANK_ACCOUNTS mba , MD_USER_TOKEN mut
WHERE mba.TOKEN_ID = mut.ID AND IS_CONSENT =1 AND ACCOUNT_STATUS =1
GROUP BY mut.BDAY_CUST_ID;






SELECT 
(SELECT COUNT(*) FROM betterday_db.MD_BANK_ACCOUNTS_DEPOSIT_TRANS_HIST WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM betterday_db.MD_BANK_ACCOUNTS
  WHERE TOKEN_ID IN (SELECT ID FROM betterday_db.MD_USER_TOKEN
  WHERE BDAY_CUST_ID = 539)
 AND IS_CONSENT=1 AND ACCOUNT_TYPE = 1001 AND ACCOUNT_STATUS=1)
 AND TRANS_TYPE =2
 AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 539), INTERVAL 4 MONTH)) AND
                                                 (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 539), INTERVAL 3 MONTH)))
-
(SELECT COUNT(DISTINCT A.ID)-- A.BANK_ACCOUNTS_ID,B.BANK_ACCOUNTS_ID, A.TRANS_DTIME, B.TRANS_DTIME,A.TRANS_AMT,B.TRANS_AMT,A.TRANS_TYPE,B.TRANS_TYPE
 FROM
 (SELECT * FROM MD_BANK_ACCOUNTS_DEPOSIT_TRANS_HIST 
        WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = 539)
        AND IS_CONSENT =1 AND ACCOUNT_TYPE = 1001 AND ACCOUNT_STATUS=1)
        AND TRANS_TYPE =2
        AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 539), INTERVAL 4 MONTH)) AND
                                                        (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 539), INTERVAL 3 MONTH))) A, -- 출금
 (SELECT * FROM MD_BANK_ACCOUNTS_DEPOSIT_TRANS_HIST 
        WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = 539)
        AND IS_CONSENT =1 AND ACCOUNT_TYPE = 1001 AND ACCOUNT_STATUS=1)
        AND TRANS_TYPE =3
        AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 539), INTERVAL 4 MONTH)) AND
                                                        (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 539), INTERVAL 3 MONTH))) B -- 입금
 WHERE A.TRANS_AMT = B.TRANS_AMT
 AND NOT (A.BANK_ACCOUNTS_ID = B.BANK_ACCOUNTS_ID)
 AND DATE_FORMAT(A.TRANS_DTIME,"%Y-%m-%d") = DATE_FORMAT(B.TRANS_DTIME,"%Y-%m-%d")) AS '총 출금횟수';






SELECT COUNT(*) FROM MD_BANK_ACCOUNTS_DEPOSIT_TRANS_HIST 
        WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = 539)
        AND IS_CONSENT =1 AND ACCOUNT_TYPE = 1001 AND ACCOUNT_STATUS=1)
        AND TRANS_TYPE =2
        AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 539), INTERVAL 4 MONTH)) AND
                                                        (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 539), INTERVAL 3 MONTH));

                                                        
SELECT COUNT(*) FROM MD_BANK_ACCOUNTS_DEPOSIT_TRANS_HIST 
        WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = 539)
        AND IS_CONSENT =1 AND ACCOUNT_TYPE = 1001 AND ACCOUNT_STATUS=1)
        AND TRANS_TYPE =2
        AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 539), INTERVAL 3 MONTH)) AND
                                                        (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 539), INTERVAL 2 MONTH));

                                        
#################################################
SELECT CSS_BANK_19(539);

# PROCEDURE
SELECT A.ID, MAX(B.CRT_DT) AS "Last Login Time"
, CSS_BANK_102(A.ID)
, CSS_BANK_103(A.ID)
, CSS_BANK_104(A.ID)
, CSS_BANK_105(A.ID)
, CSS_BANK_106(A.ID)
, CSS_BANK_107(A.ID)
FROM betterday_db.BDAY_CUST A, betterday_db.BDAY_CUST_LOGIN_HIST B
WHERE A.ID = B.CUST_ID
AND B.CUST_ID !=539
GROUP BY B.CUST_ID
ORDER BY A.ID ASC;


SELECT CSS_IRP_4(833);

SELECT CSS_IRP_5(833);
                               
SELECT CSS_BANK_95(268);
       
           
SELECT COUNT(*) FROM 
(SELECT mut.BDAY_CUST_ID , COUNT(*), SUM(miap.EVAL_AMT - miap.PURCHASE_AMT) FROM MD_INVEST_ACCOUNTS_PRODUCTS miap , MD_INVEST_ACCOUNTS mia , MD_USER_TOKEN mut 
            WHERE miap.INVEST_ACCOUNTS_ID =  mia.ID 
            AND mia.TOKEN_ID = mut.ID 
            AND mia.IS_CONSENT=1
            AND miap.PROD_TYPE IN (413, 414, 415)
            AND miap.PURCHASE_AMT - miap.EVAL_AMT>0
            GROUP BY mut.BDAY_CUST_ID) AS A;

SELECT COUNT(*) FROM 
(SELECT ID FROM BDAY_CUST) as b


SELECT                                         
((SELECT IFNULL(SUM(TRANS_AMT),0)AS TRANS_SUM FROM MD_BANK_IRPS_TRANSACTIONS_HIST
WHERE BANK_IRPS_ID IN (SELECT ID FROM MD_BANK_IRPS
                                                WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN 
                                                                                        WHERE BDAY_CUST_ID = 1174)
                                                AND IS_CONSENT=1)
AND TRANS_TYPE LIKE '02'
AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 1174), INTERVAL 6 MONTH)) AND
                                                 (SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 1174))+
(SELECT IFNULL(SUM(TRANS_AMT),0)AS TRANS_SUM FROM MD_INVEST_IRPS_TRANSACTIONS_HIST 
WHERE INVEST_IRPS_ID IN (SELECT ID FROM MD_INVEST_IRPS
                                                  WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN 
                                                                                            WHERE BDAY_CUST_ID = 1174) 
                                                  AND IS_CONSENT=1)
AND TRANS_TYPE LIKE '02'
AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 1174), INTERVAL 6 MONTH)) AND
                                                 (SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 1174))+
(SELECT IFNULL(SUM(TRANS_AMT),0)AS TRANS_SUM FROM MD_INSU_IRPS_TRANSACTIONS_HIST
WHERE INSU_IRPS_ID IN (SELECT ID FROM MD_INSU_IRPS 
                                            WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN 
                                                                                        WHERE BDAY_CUST_ID = 1174)
                                                AND IS_CONSENT=1)
AND TRANS_TYPE LIKE '02'
AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 1174), INTERVAL 6 MONTH)) AND
                                                 (SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 1174))) AS TRANS_SUM;


                                                
                                                
SELECT TRANS_AMT FROM MD_INVEST_IRPS_TRANSACTIONS_HIST 
WHERE INVEST_IRPS_ID IN (SELECT ID FROM MD_INVEST_IRPS
                                                  WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN 
                                                                                            WHERE BDAY_CUST_ID = 1174) 
                                                  AND IS_CONSENT=1)
AND TRANS_TYPE LIKE '02'
AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 1174), INTERVAL 6 MONTH)) AND
                                                 (SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 1174);

                                                 
                                                 
SELECT * FROM MD_INSU_IRPS_TRANSACTIONS_HIST
WHERE INSU_IRPS_ID IN (SELECT ID FROM MD_INSU_IRPS 
                                            WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN)
                                                AND IS_CONSENT=1)
AND TRANS_TYPE LIKE '02';

SELECT * FROM MD_INVEST_IRPS_TRANSACTIONS_HIST 
WHERE INVEST_IRPS_ID IN (SELECT ID FROM MD_INVEST_IRPS
                                                  WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN 
                                                                                            WHERE BDAY_CUST_ID = 1174));
SELECT * FROM MD_BANK_IRPS_TRANSACTIONS_HIST 
WHERE BANK_IRPS_ID IN (SELECT ID FROM MD_BANK_IRPS
                                                  WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN 
                                                                                            WHERE BDAY_CUST_ID = 1174));
                                                                                           
                                                                                           


SELECT                                         
((SELECT IFNULL(SUM(TRANS_AMT),0)AS TRANS_SUM FROM MD_BANK_IRPS_TRANSACTIONS_HIST
WHERE BANK_IRPS_ID IN (SELECT ID FROM MD_BANK_IRPS
                                                WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN 
                                                                                        WHERE BDAY_CUST_ID IN (SELECT ID FROM BDAY_CUST WHERE TRUNCATE((TO_DAYS(NOW()) - TO_DAYS(BIRTH_DD)) / 365, 0)
                                                                                        												AND ID = 1174))
                                                AND IS_CONSENT=1)
AND TRANS_TYPE LIKE '02'
AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 1174), INTERVAL 6 MONTH)) AND
                                                 (SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 1174))+
(SELECT IFNULL(SUM(TRANS_AMT),0)AS TRANS_SUM FROM MD_INVEST_IRPS_TRANSACTIONS_HIST 
WHERE INVEST_IRPS_ID IN (SELECT ID FROM MD_INVEST_IRPS 
                                                  WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN 
                                                                                            WHERE BDAY_CUST_ID IN (SELECT ID FROM BDAY_CUST WHERE TRUNCATE((TO_DAYS(NOW()) - TO_DAYS(BIRTH_DD)) / 365, 0)
                                                                                        												AND ID = 1174)) 
                                                  AND IS_CONSENT=1)
AND TRANS_TYPE LIKE '02'
AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 1174), INTERVAL 6 MONTH)) AND
                                                 (SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 1174))+
(SELECT IFNULL(SUM(TRANS_AMT),0)AS TRANS_SUM FROM MD_INSU_IRPS_TRANSACTIONS_HIST
WHERE INSU_IRPS_ID IN (SELECT ID FROM MD_INSU_IRPS 
                                            WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN 
                                                                                        WHERE BDAY_CUST_ID IN (SELECT ID FROM BDAY_CUST WHERE TRUNCATE((TO_DAYS(NOW()) - TO_DAYS(BIRTH_DD)) / 365, 0)
                                                                                        												AND ID = 1174))
                                                AND IS_CONSENT=1)
AND TRANS_TYPE LIKE '02'
AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 1174), INTERVAL 6 MONTH)) AND
                                                 (SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 1174))) AS TRANS_SUM;

SELECT CSS_IRP_7(995);
SELECT CSS_IRP_6(995);

SELECT                                         
((SELECT IFNULL(SUM(TRANS_AMT),0)AS TRANS_SUM FROM MD_BANK_IRPS_TRANSACTIONS_HIST
WHERE BANK_IRPS_ID IN (SELECT ID FROM MD_BANK_IRPS
                                                WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN 
                                                                                        WHERE BDAY_CUST_ID = 995)
                                                AND IS_CONSENT=1)
AND TRANS_TYPE LIKE '01'
AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 995), INTERVAL 6 MONTH)) AND
(SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 995) )+
(SELECT IFNULL(SUM(TRANS_AMT),0)AS TRANS_SUM FROM MD_INVEST_IRPS_TRANSACTIONS_HIST
WHERE INVEST_IRPS_ID IN (SELECT ID FROM MD_INVEST_IRPS 
                                                  WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN 
                                                                                            WHERE BDAY_CUST_ID = 995) 
                                                  AND IS_CONSENT=1)
AND TRANS_TYPE LIKE '01'
AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 995), INTERVAL 6 MONTH)) AND
(SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 995))+
(SELECT IFNULL(SUM(TRANS_AMT),0)AS TRANS_SUM FROM MD_INSU_IRPS_TRANSACTIONS_HIST
WHERE INSU_IRPS_ID IN (SELECT ID FROM MD_INSU_IRPS 
                                            WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN 
                                                                                        WHERE BDAY_CUST_ID = 995)
                                                AND IS_CONSENT=1)
AND TRANS_TYPE LIKE '01'
AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 995), INTERVAL 6 MONTH)) AND
(SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 995) )) AS TRANS_SUM ;








SELECT                                         
((SELECT IFNULL(SUM(TRANS_AMT),0)AS TRANS_SUM FROM MD_BANK_IRPS_TRANSACTIONS_HIST
WHERE BANK_IRPS_ID IN (SELECT ID FROM MD_BANK_IRPS
                                                WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN 
                                                                                        WHERE BDAY_CUST_ID = 995)
                                                AND IS_CONSENT=1)
AND TRANS_TYPE LIKE '02'
AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 995), INTERVAL 6 MONTH)) AND
                                                 (SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 995))+
(SELECT IFNULL(SUM(TRANS_AMT),0)AS TRANS_SUM FROM MD_INVEST_IRPS_TRANSACTIONS_HIST 
WHERE INVEST_IRPS_ID IN (SELECT ID FROM MD_INVEST_IRPS 
                                                  WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN 
                                                                                            WHERE BDAY_CUST_ID = 995)
                                                  AND IS_CONSENT=1)
AND TRANS_TYPE = '02'
AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 995), INTERVAL 6 MONTH)) AND
                                                 (SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 995))+
(SELECT IFNULL(SUM(TRANS_AMT),0)AS TRANS_SUM FROM MD_INSU_IRPS_TRANSACTIONS_HIST
WHERE INSU_IRPS_ID IN (SELECT ID FROM MD_INSU_IRPS 
                                            WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN 
                                                                                        WHERE BDAY_CUST_ID = 995)
                                                AND IS_CONSENT=1)
AND TRANS_TYPE LIKE '02'
AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 995), INTERVAL 6 MONTH)) AND
                                                 (SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 995))) AS TRANS_SUM;

                                                
                                                
(SELECT *  FROM MD_INVEST_IRPS_TRANSACTIONS_HIST 
WHERE INVEST_IRPS_ID IN (SELECT ID FROM MD_INVEST_IRPS 
                                                  WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN 
                                                                                            WHERE BDAY_CUST_ID = 237)
                                                  AND IS_CONSENT=1)
AND TRANS_TYPE = '02'
AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 237), INTERVAL 6 MONTH)) AND
                                                 (SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 237))
                                                 
                                                 
(SELECT *  FROM MD_INVEST_IRPS_TRANSACTIONS_HIST 
WHERE INVEST_IRPS_ID IN (SELECT ID FROM MD_INVEST_IRPS 
                                                  WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN 
                                                                                            WHERE BDAY_CUST_ID = 237)
                                                  AND IS_CONSENT=1)
AND TRANS_TYPE = '01'
AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 237), INTERVAL 6 MONTH)) AND
                                                 (SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 237))
                                                

SELECT CSS_BANK_48(944);

SELECT * FROM BDAY_CUST
WHERE ID = 944
              
SELECT 
(SELECT IF((SELECT COUNT(*) FROM  MD_BANK_ACCOUNTS_DEPOSIT_TRANS_HIST WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS
        WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = VAR_BDAY_CUST_ID)
        AND IS_CONSENT = 1))=0,NULL,COUNT(*)) FROM betterday_db.MD_BANK_ACCOUNTS_DEPOSIT_TRANS_HIST WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM betterday_db.MD_BANK_ACCOUNTS
  WHERE TOKEN_ID IN (SELECT ID FROM betterday_db.MD_USER_TOKEN
  WHERE BDAY_CUST_ID = VAR_BDAY_CUST_ID)
 AND IS_CONSENT=1 AND ACCOUNT_TYPE = 1001 AND ACCOUNT_STATUS=1)
 AND TRANS_TYPE =3
 AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = VAR_BDAY_CUST_ID), INTERVAL 5 MONTH)) AND
                                                 (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = VAR_BDAY_CUST_ID), INTERVAL 4 MONTH)))
-
(SELECT IF((SELECT COUNT(*) FROM  MD_BANK_ACCOUNTS_DEPOSIT_TRANS_HIST WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS
        WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = VAR_BDAY_CUST_ID)
        AND IS_CONSENT = 1))=0,NULL,COUNT(DISTINCT A.ID))-- A.BANK_ACCOUNTS_ID,B.BANK_ACCOUNTS_ID, A.TRANS_DTIME, B.TRANS_DTIME,A.TRANS_AMT,B.TRANS_AMT,A.TRANS_TYPE,B.TRANS_TYPE
 FROM
 (SELECT * FROM MD_BANK_ACCOUNTS_DEPOSIT_TRANS_HIST 
        WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = VAR_BDAY_CUST_ID)
        AND IS_CONSENT =1 AND ACCOUNT_TYPE = 1001 AND ACCOUNT_STATUS=1)
        AND TRANS_TYPE =2
        AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = VAR_BDAY_CUST_ID), INTERVAL 5 MONTH)) AND
                                                        (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = VAR_BDAY_CUST_ID), INTERVAL 4 MONTH))) A, -- 출금
 (SELECT * FROM MD_BANK_ACCOUNTS_DEPOSIT_TRANS_HIST 
        WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = VAR_BDAY_CUST_ID)
        AND IS_CONSENT =1 AND ACCOUNT_TYPE = 1001 AND ACCOUNT_STATUS=1)
        AND TRANS_TYPE =3
        AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = VAR_BDAY_CUST_ID), INTERVAL 5 MONTH)) AND
                                                        (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = VAR_BDAY_CUST_ID), INTERVAL 4 MONTH))) B -- 입금
 WHERE A.TRANS_AMT = B.TRANS_AMT
 AND NOT (A.BANK_ACCOUNTS_ID = B.BANK_ACCOUNTS_ID)
 AND DATE_FORMAT(A.TRANS_DTIME,"%Y-%m-%d") = DATE_FORMAT(B.TRANS_DTIME,"%Y-%m-%d")) AS '총 출금횟수';
 

SELECT * FROM MD_BANK_ACCOUNTS_LOAN_DETAIL a, MD_BANK_ACCOUNTS b
WHERE a.BANK_ACCOUNTS_ID =b.ID AND ACCOUNT_TYPE =3120;

SELECT *FROM MD_BANK_ACCOUNTS WHERE ACCOUNT_TYPE =3210;

SELECT * FROM MD_BANK_ACCOUNTS_DEPOSIT_TRANS_HIST 
WHERE TRANS_MEMO NOT LIKE '%페이%'
AND TRANS_MEMO NOT LIKE '%체크%'
AND TRANS_MEMO NOT LIKE '%후불교통%'
AND TRANS_MEMO NOT LIKE '%교통카드%'
AND TRANS_MEMO NOT LIKE '%교통이용%'


SELECT CSS_BANK_28(6481);

SELECT 
(SELECT IF((SELECT COUNT(*) FROM  MD_BANK_ACCOUNTS_DEPOSIT_TRANS_HIST WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS
        WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = VAR_BDAY_CUST_ID)
        AND IS_CONSENT = 1)AND TRANS_MEMO NOT LIKE '%페이%'
							AND TRANS_MEMO NOT LIKE '%체크%'
							AND TRANS_MEMO NOT LIKE '%후불교통%'
							AND TRANS_MEMO NOT LIKE '%교통카드%'
							AND TRANS_MEMO NOT LIKE '%교통이용%')=0,NULL,COUNT(*)) FROM betterday_db.MD_BANK_ACCOUNTS_DEPOSIT_TRANS_HIST WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM betterday_db.MD_BANK_ACCOUNTS
  WHERE TOKEN_ID IN (SELECT ID FROM betterday_db.MD_USER_TOKEN
  WHERE BDAY_CUST_ID = VAR_BDAY_CUST_ID)
 AND IS_CONSENT=1 AND ACCOUNT_TYPE = 1001 AND ACCOUNT_STATUS=1)AND TRANS_MEMO NOT LIKE '%페이%'
							AND TRANS_MEMO NOT LIKE '%체크%'
							AND TRANS_MEMO NOT LIKE '%후불교통%'
							AND TRANS_MEMO NOT LIKE '%교통카드%'
							AND TRANS_MEMO NOT LIKE '%교통이용%'
 AND TRANS_TYPE =3
 AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = VAR_BDAY_CUST_ID), INTERVAL 5 MONTH)) AND
                                                 (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = VAR_BDAY_CUST_ID), INTERVAL 4 MONTH)))
-
(SELECT IF((SELECT COUNT(*) FROM  MD_BANK_ACCOUNTS_DEPOSIT_TRANS_HIST WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS
        WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = VAR_BDAY_CUST_ID)
        AND IS_CONSENT = 1)AND TRANS_MEMO NOT LIKE '%페이%'
							AND TRANS_MEMO NOT LIKE '%체크%'
							AND TRANS_MEMO NOT LIKE '%후불교통%'
							AND TRANS_MEMO NOT LIKE '%교통카드%'
							AND TRANS_MEMO NOT LIKE '%교통이용%')=0,NULL,COUNT(DISTINCT A.ID))-- A.BANK_ACCOUNTS_ID,B.BANK_ACCOUNTS_ID, A.TRANS_DTIME, B.TRANS_DTIME,A.TRANS_AMT,B.TRANS_AMT,A.TRANS_TYPE,B.TRANS_TYPE
 FROM
 (SELECT * FROM MD_BANK_ACCOUNTS_DEPOSIT_TRANS_HIST 
        WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = VAR_BDAY_CUST_ID)
        AND IS_CONSENT =1 AND ACCOUNT_TYPE = 1001 AND ACCOUNT_STATUS=1)AND TRANS_MEMO NOT LIKE '%페이%'
							AND TRANS_MEMO NOT LIKE '%체크%'
							AND TRANS_MEMO NOT LIKE '%후불교통%'
							AND TRANS_MEMO NOT LIKE '%교통카드%'
							AND TRANS_MEMO NOT LIKE '%교통이용%'
        AND TRANS_TYPE =2
        AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = VAR_BDAY_CUST_ID), INTERVAL 5 MONTH)) AND
                                                        (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = VAR_BDAY_CUST_ID), INTERVAL 4 MONTH))) A, -- 출금
 (SELECT * FROM MD_BANK_ACCOUNTS_DEPOSIT_TRANS_HIST 
        WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = VAR_BDAY_CUST_ID)
        AND IS_CONSENT =1 AND ACCOUNT_TYPE = 1001 AND ACCOUNT_STATUS=1)AND TRANS_MEMO NOT LIKE '%페이%'
							AND TRANS_MEMO NOT LIKE '%체크%'
							AND TRANS_MEMO NOT LIKE '%후불교통%'
							AND TRANS_MEMO NOT LIKE '%교통카드%'
							AND TRANS_MEMO NOT LIKE '%교통이용%'
        AND TRANS_TYPE =3
        AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = VAR_BDAY_CUST_ID), INTERVAL 5 MONTH)) AND
                                                        (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = VAR_BDAY_CUST_ID), INTERVAL 4 MONTH))) B -- 입금
 WHERE A.TRANS_AMT = B.TRANS_AMT
 AND NOT (A.BANK_ACCOUNTS_ID = B.BANK_ACCOUNTS_ID)
 AND DATE_FORMAT(A.TRANS_DTIME,"%Y-%m-%d") = DATE_FORMAT(B.TRANS_DTIME,"%Y-%m-%d")) AS '총 출금횟수' INTO BANK_28;


SELECT A.ID, MAX(B.CRT_DT) AS "Last Login Time"
, CSS_BANK_18(A.ID) AS A1
, CSS_BANK_19(A.ID)
, CSS_BANK_20(A.ID)
, CSS_BANK_21(A.ID)
, CSS_BANK_22(A.ID)
, CSS_BANK_23(A.ID)
FROM betterday_db.BDAY_CUST A, betterday_db.BDAY_CUST_LOGIN_HIST B
WHERE A.ID = B.CUST_ID
AND B.CUST_ID !=539
GROUP BY B.CUST_ID
ORDER BY A.ID ASC;


# 36 입금 query
SELECT SUM(TRANS_AMT) FROM betterday_db.MD_BANK_ACCOUNTS_DEPOSIT_TRANS_HIST WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM betterday_db.MD_BANK_ACCOUNTS
  WHERE TOKEN_ID IN (SELECT ID FROM betterday_db.MD_USER_TOKEN
  WHERE BDAY_CUST_ID = 10)
 AND IS_CONSENT=1 AND ACCOUNT_TYPE = 1001 AND ACCOUNT_STATUS=1)
 AND TRANS_TYPE =3
 AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 10), INTERVAL 1 MONTH)) AND
                                                 (SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 10);

                                                
SELECT SUM(TRANS_AMT) FROM MD_BANK_ACCOUNTS_DEPOSIT_TRANS_HIST 
WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = 10)
        AND IS_CONSENT =1 AND ACCOUNT_TYPE = 1001 AND ACCOUNT_STATUS=1)
        AND TRANS_TYPE =3
        AND (TRANS_MEMO LIKE '%급여%' OR TRANS_MEMO LIKE '%월급%' OR TRANS_MEMO LIKE '%성과급%' OR TRANS_MEMO LIKE '%인센티브%' OR TRANS_MEMO LIKE '%보너스%' OR TRANS_MEMO LIKE '%상여%' OR TRANS_MEMO LIKE '%연차%' OR TRANS_MEMO LIKE '%연말정산%' OR TRANS_MEMO LIKE '%소급%')
        AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 10), INTERVAL 1 MONTH)) AND
                                                 (SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 10);

(SELECT IFNULL(SUM(IF(TRANS_AMT>20000000,20000000,TRANS_AMT)),0) FROM
(SELECT DISTINCT A.ID, A.TRANS_AMT-- A.BANK_ACCOUNTS_ID,B.BANK_ACCOUNTS_ID, A.TRANS_DTIME, B.TRANS_DTIME,A.TRANS_AMT,B.TRANS_AMT,A.TRANS_TYPE,B.TRANS_TYPE
 FROM
 (SELECT * FROM MD_BANK_ACCOUNTS_DEPOSIT_TRANS_HIST
        WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = 10)
        AND IS_CONSENT =1 AND ACCOUNT_TYPE = 1001 AND ACCOUNT_STATUS=1)AND TRANS_MEMO NOT LIKE '%페이%'
							AND TRANS_MEMO NOT LIKE '%체크%'
							AND TRANS_MEMO NOT LIKE '%후불교통%'
							AND TRANS_MEMO NOT LIKE '%교통카드%'
							AND TRANS_MEMO NOT LIKE '%교통이용%'
        AND TRANS_TYPE =2
        AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 10), INTERVAL 1 MONTH)) AND
                                                        (SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 10)) A, -- 출금
 (SELECT * FROM MD_BANK_ACCOUNTS_DEPOSIT_TRANS_HIST 
        WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = 10)
        AND IS_CONSENT =1 AND ACCOUNT_TYPE = 1001 AND ACCOUNT_STATUS=1)AND TRANS_MEMO NOT LIKE '%페이%'
							AND TRANS_MEMO NOT LIKE '%체크%'
							AND TRANS_MEMO NOT LIKE '%후불교통%'
							AND TRANS_MEMO NOT LIKE '%교통카드%'
							AND TRANS_MEMO NOT LIKE '%교통이용%'
        AND TRANS_TYPE =3
        AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 10), INTERVAL 1 MONTH)) AND
                                                        (SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 10)) B -- 입금
 WHERE A.TRANS_AMT = B.TRANS_AMT
 AND NOT (A.BANK_ACCOUNTS_ID = B.BANK_ACCOUNTS_ID)
 AND DATE_FORMAT(A.TRANS_DTIME,"%Y-%m-%d") = DATE_FORMAT(B.TRANS_DTIME,"%Y-%m-%d")) C)

SELECT CSS_BANK_36(10), CSS_BANK_42(10);



SELECT *
FROM MD_BANK_ACCOUNTS_DEPOSIT_TRANS_HIST mbadt
LEFT OUTER JOIN MD_BANK_ACCOUNTS mba 
ON mbadt.BANK_ACCOUNTS_ID = mba.ID
WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS
        WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = 690)
        AND IS_CONSENT = 1)
AND mba.ACCOUNT_TYPE = 1001
AND mba.ACCOUNT_STATUS = 1
AND mbadt.BALANCE_AMT = 0
AND TRANS_TYPE = 2
AND TRANS_MEMO LIKE '%카드%'
AND mbadt.TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 690), INTERVAL 1 MONTH)) AND
                                                          (SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 690);


SELECT A.ID, MAX(B.CRT_DT) AS "Last Login Time"
, CSS_BANK_83(A.ID)
FROM betterday_db.BDAY_CUST A, betterday_db.BDAY_CUST_LOGIN_HIST B
WHERE A.ID = B.CUST_ID
AND B.CUST_ID !=539
GROUP BY B.CUST_ID
ORDER BY A.ID ASC;


SELECT SUM(TRANS_AMT)
FROM MD_BANK_ACCOUNTS_DEPOSIT_TRANS_HIST mbadt
LEFT OUTER JOIN MD_BANK_ACCOUNTS mba 
ON mbadt.BANK_ACCOUNTS_ID = mba.ID
WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS
        WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = VAR_BDAY_CUST_ID)
        AND IS_CONSENT = 1)
AND mba.ACCOUNT_TYPE = 1001
AND mba.ACCOUNT_STATUS = 1
AND TRANS_TYPE = 2
AND ((TRANS_MEMO LIKE '%생명보험%')
        OR (TRANS_MEMO LIKE '%생보%')
        OR (TRANS_MEMO LIKE '%손해보험%')
        OR (TRANS_MEMO LIKE '%손보%')
        OR (TRANS_MEMO LIKE '%라이프%')
        OR (TRANS_MEMO LIKE '%화재%')
        OR (TRANS_MEMO LIKE '%해상%'))
AND ((TRANS_MEMO NOT LIKE '%건강보험%')
        AND (TRANS_MEMO NOT LIKE '%약관%')
        AND (TRANS_MEMO NOT LIKE '%대출%')
        AND (TRANS_MEMO NOT LIKE '%약대%'))
AND mbadt.TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = VAR_BDAY_CUST_ID), INTERVAL 1 MONTH)) AND
                                                (SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = VAR_BDAY_CUST_ID);

                                               
#환율 계산해야함, 114                                           
SELECT SUM(IF(CURRENCY_CODE='KRW' OR CURRENCY_CODE=NULL,EVAL_AMT,EVAL_AMT*(SELECT RATE FROM betterday_db.BD_EXCHANGE_RATE B
					WHERE B.CURRENCY_CODE = mbaid.CURRENCY_CODE
					AND date_format(CRT_DT,"%Y-%m-%d") = DATE
					limit 1))) AS EVAL_SUM
FROM MD_BANK_ACCOUNTS mba,MD_BANK_ACCOUNTS_INVEST_DETAIL mbaid
WHERE mbaid.BANK_ACCOUNTS_ID = mb	
AND BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS
        WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = 13)
        AND IS_CONSENT = 1)
AND mba.ACCOUNT_TYPE IN (2001, 2002, 2003, 2004, 2999);

SELECT * FROM MD_BANK_ACCOUNTS_INVEST_DETAIL


#환율 계산해야함, 114                                           
SELECT SUM(IF(CURRENCY_CODE='KRW' OR CURRENCY_CODE=NULL,EVAL_AMT,EVAL_AMT*(SELECT RATE FROM betterday_db.BD_EXCHANGE_RATE B
					WHERE B.CURRENCY_CODE = mbaid.CURRENCY_CODE
					AND date_format(CRT_DT,"%Y-%m-%d") = mbaid.ISSUE_DATE 
					limit 1))) AS EVAL_SUM
FROM MD_BANK_ACCOUNTS mba, (SELECT * FROM MD_BANK_ACCOUNTS_INVEST_BASIC mbaib LEFT JOIN MD_BANK_ACCOUNTS_INVEST_DETAIL mbaid ON mbaib.BANK_ACCOUNTS_ID = mbaid.BANK_ACCOUNTS_ID) AS mbaid
WHERE mbaid.BANK_ACCOUNTS_ID = mba.ID
AND BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS
        WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = 13)
        AND IS_CONSENT = 1)
AND mba.ACCOUNT_TYPE IN (2001, 2002, 2003, 2004, 2999);




SELECT B.BDAY_CUST_ID,SUM(IF(CURRENCY_CODE='KRW' OR CURRENCY_CODE=NULL,EVAL_AMT,EVAL_AMT*(SELECT RATE FROM betterday_db.BD_EXCHANGE_RATE B
					WHERE B.CURRENCY_CODE = A.CURRENCY_CODE
					AND date_format(CRT_DT,"%Y-%m-%d") = A.BASE_DATE 
					limit 1))) AS EVAL_SUM
     FROM betterday_db.MD_INVEST_ACCOUNTS_PRODUCTS A, betterday_db.MD_USER_TOKEN B, betterday_db.MD_INVEST_ACCOUNTS C
     WHERE B.ID = C.TOKEN_ID
     AND C.ID = A.INVEST_ACCOUNTS_ID
     GROUP BY BDAY_CUST_ID;

SELECT * FROM MD_BANK_ACCOUNTS_INVEST_DETAIL;
SELECT * FROM MD_BANK_ACCOUNTS_INVEST_BASIC;

    
SELECT A.ID
, CSS_BANK_97(A.ID)/CSS_BANK_17(A.ID) AS a
FROM betterday_db.BDAY_CUST A, betterday_db.BDAY_CUST_LOGIN_HIST B
WHERE A.ID = B.CUST_ID
AND B.CUST_ID !=539
GROUP BY B.CUST_ID
ORDER BY a DESC;


SELECT SUM(TRANS_AMT)
FROM MD_BANK_ACCOUNTS_DEPOSIT_TRANS_HIST mbadt
LEFT OUTER JOIN MD_BANK_ACCOUNTS mba 
ON mbadt.BANK_ACCOUNTS_ID = mba.ID
WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS
        WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = 10)
        AND IS_CONSENT = 1)
AND mba.ACCOUNT_TYPE = 1001
AND mba.ACCOUNT_STATUS = 1
AND TRANS_TYPE = 2
AND ((TRANS_MEMO LIKE '%지방세%')
        OR (TRANS_MEMO LIKE '%국세%'))
AND mbadt.TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 10), INTERVAL 12 MONTH)) AND
                                                (SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 10);
  
                                               
SELECT SUM(IF(B.CURRENCY_CODE='KRW' OR B.CURRENCY_CODE=NULL,EVAL_AMT,EVAL_AMT*(SELECT RATE FROM betterday_db.BD_EXCHANGE_RATE E
					WHERE E.CURRENCY_CODE = B.CURRENCY_CODE
					AND date_format(CRT_DT,"%Y-%m-%d") = B.BASE_DATE 
					limit 1))) AS EVAL_SUM 
FROM MD_INVEST_ACCOUNTS_TRANS_HIST A, MD_INVEST_ACCOUNTS_PRODUCTS B, MD_USER_TOKEN C, MD_INVEST_ACCOUNTS D
WHERE A.PROD_CODE = B.PROD_CODE
AND A.INVEST_ACCOUNTS_ID = B.INVEST_ACCOUNTS_ID
AND C.ID = D.TOKEN_ID
AND D.ID = B.INVEST_ACCOUNTS_ID
AND C.BDAY_CUST_ID = 173
AND DATE_ADD(A.TRANS_DTIME, INTERVAL 9 HOUR)
        BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 173), INTERVAL 1 MONTH))
        AND (SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 173)
AND A.TRANS_TYPE = 342
AND B.PROD_TYPE = 402;

 
SELECT CSS_INV_32(21);



SELECT SUM(TRANS_AMT) FROM MD_INVEST_ACCOUNTS_TRANS_HIST
WHERE INVEST_ACCOUNTS_ID IN (SELECT ID FROM MD_INVEST_ACCOUNTS
                                                          WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN
                                                                                                   WHERE BDAY_CUST_ID = 132)
                                                          AND IS_CONSENT=1)
AND PROD_CODE >='403' AND PROD_CODE<='421'
AND TRANS_TYPE ='301'
AND TRANS_DTIME
	BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 132), INTERVAL 6 MONTH))
	AND (SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 132);




SELECT SUM(TRANS_AMT) FROM MD_INVEST_ACCOUNTS_TRANS_HIST
WHERE INVEST_ACCOUNTS_ID IN (SELECT ID FROM MD_INVEST_ACCOUNTS
                                                          WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN
                                                                                                   WHERE BDAY_CUST_ID = 132)
                                                          AND IS_CONSENT=1)
AND PROD_CODE >='403' AND PROD_CODE<='421'
AND TRANS_TYPE ='301'
AND TRANS_DTIME
	BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 132), INTERVAL 6 MONTH))
	AND (SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 132);


SELECT* FROM MD_BANK_ACCOUNTS mba, MD_USER_TOKEN mut
            WHERE mba.TOKEN_ID = mut.ID;




SELECT A.ID
, CSS_BANK_36(A.ID) AS 'M0_입금'
, CSS_BANK_30(A.ID) AS 'M0_출금'
, CSS_BANK_37(A.ID) AS 'M1_입금'
, CSS_BANK_31(A.ID) AS 'M1_출금'
FROM betterday_db.BDAY_CUST A, betterday_db.BDAY_CUST_LOGIN_HIST B
WHERE A.ID = B.CUST_ID
AND B.CUST_ID !=539
GROUP BY B.CUST_ID
ORDER BY A.ID ASC;

SELECT A.ID
, CSS_BANK_123(A.ID) + CSS_BANK_123(A.ID) 
FROM betterday_db.BDAY_CUST A, betterday_db.BDAY_CUST_LOGIN_HIST B
WHERE A.ID = B.CUST_ID
AND B.CUST_ID !=539
GROUP BY B.CUST_ID
ORDER BY A.ID ASC;


SELECT A.ID
, CSS_BANK_107(A.ID)
FROM betterday_db.BDAY_CUST A, betterday_db.BDAY_CUST_LOGIN_HIST B
WHERE A.ID = B.CUST_ID
AND B.CUST_ID !=539
GROUP BY B.CUST_ID
ORDER BY A.ID ASC;

-- CSS_BANK_114 ~ CSS_BANK_118: 환율 계산때문에 보류
-- BANK 이외 환율 계산이 필요한 항목에 대해서는 수정 완료(사용TABLE에 날짜에 대한 값이 존재하기 때문에)


SELECT SUM(BALANCE_AMT) INTO INS_23 FROM MD_INSU_LOANS_DETAIL 
WHERE INSU_LOANS_ID IN (SELECT ID FROM MD_INSU_LOANS 
                                                        WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN 
                                                                                                WHERE BDAY_CUST_ID = VAR_BDAY_CUST_ID)
                                                        AND IS_CONSENT=1
                                                        AND ACCOUNT_TYPE =3240);

SELECT IF(CSS_BANK_102(846)>1 AND CSS_BANK_103(846)>1,1, 0)+
IF(CSS_BANK_103(846)>1 AND CSS_BANK_104(846)>1,1, 0)+
IF(CSS_BANK_104(846)>1 AND CSS_BANK_105(846)>1,1, 0)+
IF(CSS_BANK_105(846)>1 AND CSS_BANK_106(846)>1,1, 0)+
IF(CSS_BANK_106(846)>1 AND CSS_BANK_107(846)>1,1, 0);


SELECT CSS_BANK_102(846),
CSS_BANK_103(846),
CSS_BANK_104(846),
CSS_BANK_105(846),
CSS_BANK_106(846), CSS_BANK_107(846);

-- 846, 1032, 1896

SELECT A.ID
, CSS_BANK_102(A.ID)
, CSS_BANK_103(A.ID)
, CSS_BANK_104(A.ID)
, CSS_BANK_105(A.ID)
, CSS_BANK_106(A.ID)
, CSS_BANK_107(A.ID)
FROM betterday_db.BDAY_CUST A, betterday_db.BDAY_CUST_LOGIN_HIST B
WHERE A.ID = B.CUST_ID
AND B.CUST_ID !=539
GROUP BY B.CUST_ID
ORDER BY A.ID ASC;


SELECT A.ID
, CSS_BANK_138(A.ID)
FROM betterday_db.BDAY_CUST A, betterday_db.BDAY_CUST_LOGIN_HIST B
WHERE A.ID = B.CUST_ID
AND B.CUST_ID !=539
GROUP BY B.CUST_ID
ORDER BY A.ID ASC;

# 157-517-625-846-1032-1049

SELECT COUNT(*) FROM MD_BANK_ACCOUNTS_LOAN_TRANS_HIST mbalth 
WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = 110) AND IS_CONSENT=1)
AND INT_TYPE =3
AND TRANS_DTIME
	BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 110), INTERVAL 6 MONTH))
	AND (SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 110);
	

SELECT SUM(EVAL_AMT*(SELECT if(IFNULL(CURRENCY_CODE, 'KRW')='KRW', 1, (SELECT RATE FROM betterday_db.BD_EXCHANGE_RATE as A1 WHERE A1.CURRENCY_CODE = mbaid.CURRENCY_CODE ORDER BY CRT_DT DESC LIMIT 1))))
FROM MD_BANK_ACCOUNTS_INVEST_DETAIL mbaid
LEFT OUTER JOIN MD_BANK_ACCOUNTS mba 
ON mbaid.BANK_ACCOUNTS_ID = mba.ID
WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS
        WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = 10)
        AND IS_CONSENT = 1)
AND mba.ACCOUNT_TYPE IN (2001, 2002, 2003, 2004, 2999);



SELECT SUM(IF(mbait.CURRENCY_CODE='KRW' OR mbait.CURRENCY_CODE=NULL,TRANS_AMT,TRANS_AMT*(SELECT RATE FROM betterday_db.BD_EXCHANGE_RATE B
					WHERE B.CURRENCY_CODE = mbait.CURRENCY_CODE
					AND date_format(CRT_DT,"%Y-%m-%d") = mbait.TRANS_DTIME 
					limit 1))) AS AMT_SUM
FROM MD_BANK_ACCOUNTS_INVEST_TRANS_HIST mbait
LEFT OUTER JOIN MD_BANK_ACCOUNTS mba 
ON mbait.BANK_ACCOUNTS_ID = mba.ID
WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS
        WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = 10)
        AND IS_CONSENT = 1)
AND mba.ACCOUNT_TYPE IN (2001,2002,2003,2004,2999)
AND mbait.TRANS_TYPE = 1
AND mbait.TRANS_DTIME BETWEEN DATE_SUB(NOW(), INTERVAL 6 MONTH) AND NOW();




SELECT SUM((INT_AMT*INT_RATE)/2)
FROM MD_CARD_LOANS_LONG_TERM mcllt  
WHERE CRT_ID IN (SELECT CRT_ID
        FROM MD_CARD_CARDS
        WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN WHERE BDAY_CUST_ID = 10) AND IS_CONSENT = 1);
      

SELECT SUM(LOAN_AMT*(1+INT_RATE)) FROM MD_CARD_LOANS_SHORT_TERM 
WHERE CRT_ID IN (SELECT CRT_ID FROM MD_CARD_CARDS 
					WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN 
										WHERE BDAY_CUST_ID = 10)
					AND IS_CONSENT =1);


SELECT SUM((LOAN_AMT-BALANCE_AMT)/PERIOD_DIFF(DATE_FORMAT((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 1354), '%Y%m'), DATE_FORMAT(mcllt.LOAN_DTIME, '%Y%m')))*6
FROM MD_CARD_LOANS_LONG_TERM mcllt
LEFT OUTER JOIN BDAY_CUST_LOGIN_HIST bclh ON mcllt.TOKEN_ID = bclh.ID
WHERE TOKEN_ID IN (SELECT ID FROM betterday_db.MD_USER_TOKEN WHERE BDAY_CUST_ID = 1354)


SELECT A.ID
, CSS_CARD_108(A.ID)
, CSS_CARD_108(A.ID)
, CSS_CARD_108(A.ID)
FROM betterday_db.BDAY_CUST A, betterday_db.BDAY_CUST_LOGIN_HIST B
WHERE A.ID = B.CUST_ID
AND B.CUST_ID !=539
GROUP BY B.CUST_ID
ORDER BY A.ID ASC;
##########################################################################################################
SELECT SUM(TRANS_AMT) FROM MD_BANK_ACCOUNTS_DEPOSIT_TRANSACTIONS
WHERE BANK_ACCOUNTS_ID IN (SELECT ID FROM MD_BANK_ACCOUNTS
							WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN
												WHERE BDAY_CUST_ID IN (SELECT mut.BDAY_CUST_ID  FROM MD_INSU_INSURANCES_BASIC miib , MD_INSU_INSURANCES mii, MD_USER_TOKEN mut, BDAY_CUST bc
																		WHERE miib.INSU_INSURANCES_ID=mii.ID
																		AND mii.TOKEN_ID = mut.ID
																		AND mut.BDAY_CUST_ID = bc.ID
																		AND TRUNCATE((TO_DAYS(NOW()) - TO_DAYS(bc.BIRTH_DD)) / 365, 0)>=55
																		AND mii.INSU_TYPE IN (09,10)
																		#AND miib.PENSION_RCV_CYCLE LIKE '1M'
																		AND mut.BDAY_CUST_ID = 7098))
							AND ACCOUNT_TYPE = 1001)
AND TRANS_DTIME BETWEEN (SELECT DATE_SUB((SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 7098), INTERVAL 6 MONTH)) AND
                                                (SELECT DATE_ADD(MAX(bclh.CRT_DT), INTERVAL 9 HOUR) FROM BDAY_CUST_LOGIN_HIST bclh WHERE CUST_ID = 7098)
AND TRANS_TYPE =3
AND TRANS_MEMO NOT LIKE '%급여%' AND TRANS_MEMO NOT LIKE '%국민연금%' AND TRANS_MEMO NOT LIKE '%퇴직연금%'
AND TRANS_MEMO REGEXP '연금|교보생명보험|	흥국생명보험|삼성생명보험|신한라이프생명보험|라이나생명보험|IBK연금보험|농협생명보험|처브라이프생명보험|메트라이프생명|DB생명보험|동양생명보험|ABL생명보험|하나생명보험|미래에셋생명보험|AIA생명보험|교보라이프|푸르덴셜생명보험|우체국보험|BNP파리바카디프생명|KDB생명보험|DGB생명보험|KB생명보험|푸본현대생명|한화생명보험|AIG손해보험|현대해상|롯데손해보험|AXA손해보험|메리츠화재해상보험|한화손해보험|DB손해보험|삼성화재해상보험주식회사|MG손해보험|캐롯손해보험|KB손해보험|흥국화재해상보험|농협손해보험';

##########################################################################################################
SELECT * FROM MD_BANK_ACCOUNTS_DEPOSIT_TRANSACTIONS
WHERE BANK_ACCOUNTS_ID IN(SELECT ID FROM MD_BANK_ACCOUNTS
							WHERE TOKEN_ID IN (SELECT ID FROM MD_USER_TOKEN 
												WHERE BDAY_CUST_ID = 779))
AND TRANS_MEMO LIKE '삼성화연금지급'

############################################################################
SELECT miib.PENSION_RCV_CYCLE , mut.BDAY_CUST_ID  FROM MD_INSU_INSURANCES_BASIC miib , MD_INSU_INSURANCES mii, MD_USER_TOKEN mut, BDAY_CUST bc
																		WHERE miib.INSU_INSURANCES_ID=mii.ID
																		AND mii.TOKEN_ID = mut.ID
																		AND mut.BDAY_CUST_ID = bc.ID
																		AND TRUNCATE((TO_DAYS(NOW()) - TO_DAYS(bc.BIRTH_DD)) / 365, 0)>=55
																		AND mii.INSU_TYPE IN (09,10)
																		#AND miib.PENSION_RCV_CYCLE LIKE '6M'
																		GROUP BY mut.BDAY_CUST_ID

## 투자 상품에 대한 금액 계산한 방법
SELECT mut.BDAY_CUST_ID, bc.BIRTH_DD 
,SUM(IF(IFNULL(CURRENCY_CODE, 'KRW')='KRW',EVAL_AMT,EVAL_AMT*(SELECT RATE FROM betterday_db.BD_EXCHANGE_RATE B
					WHERE B.CURRENCY_CODE = miap.CURRENCY_CODE
					AND date_format(CRT_DT,"%Y-%m-%d") = miap.BASE_DATE 
					limit 1))) AS AMT_SUM
FROM MD_INVEST_ACCOUNTS mia, MD_USER_TOKEN mut, MD_INVEST_ACCOUNTS_PRODUCTS miap , BDAY_CUST bc 
WHERE mia.TOKEN_ID = mut.ID  AND miap.INVEST_ACCOUNTS_ID = mia.ID AND bc.ID = mut.BDAY_CUST_ID
GROUP BY mut.BDAY_CUST_ID;

           
## 고객별로 총 자산을 구하는 쿼리
SELECT mut.BDAY_CUST_ID, SUM(IF(mbadd.BALANCE_AMT<0,0,mbadd.BALANCE_AMT)) FROM MD_BANK_ACCOUNTS_DEPOSIT_DETAIL mbadd, MD_BANK_ACCOUNTS mba , MD_USER_TOKEN mut 
WHERE mbadd.BANK_ACCOUNTS_ID = mba.ID  AND mba.TOKEN_ID = mut.ID
AND mba.IS_CONSENT=1
-- AND mba.ACCOUNT_TYPE =1001
AND mba.ACCOUNT_STATUS =1
GROUP BY mut.BDAY_CUST_ID;



SELECT * FROM MD_INVEST_ACCOUNTS mia, MD_USER_TOKEN mut, MD_INVEST_ACCOUNTS_PRODUCTS miap , BDAY_CUST bc 
            WHERE mia.TOKEN_ID = mut.ID  AND miap.INVEST_ACCOUNTS_ID = mia.ID AND bc.ID = mut.BDAY_CUST_ID
            AND mut.BDAY_CUST_ID=10;


SELECT * FROM MD_INVEST_ACCOUNTS_PRODUCTS



SELECT mut.BDAY_CUST_ID, SUM(IF(mbadd.BALANCE_AMT<0,0,mbadd.BALANCE_AMT))AS 'ACCOUNT_AMT'
FROM MD_BANK_ACCOUNTS_DEPOSIT_DETAIL mbadd, MD_BANK_ACCOUNTS mba , MD_USER_TOKEN mut 
WHERE mbadd.BANK_ACCOUNTS_ID = mba.ID
AND mba.TOKEN_ID = mut.ID
AND mba.IS_CONSENT=1
AND mba.ACCOUNT_TYPE IN (1001,1002,1003,1999,2001,2002,2003,2004,2999)
AND mba.ACCOUNT_STATUS =1
GROUP BY mut.BDAY_CUST_ID;


SELECT mut.BDAY_CUST_ID, SUM(IF(mbaid.BALANCE_AMT<0,0,mbaid.BALANCE_AMT)) AS 'INVEST_AMT'
FROM MD_BANK_ACCOUNTS_INVEST_DETAIL mbaid, MD_BANK_ACCOUNTS mba , MD_USER_TOKEN mut 
WHERE mbaid.BANK_ACCOUNTS_ID = mba.ID  AND mba.TOKEN_ID = mut.ID
AND mba.IS_CONSENT=1
AND mba.ACCOUNT_TYPE IN (1001,1002,1003,1999,2001,2002,2003,2004,2999)
AND mba.ACCOUNT_STATUS =1
GROUP BY mut.BDAY_CUST_ID;
